---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: testjob
    spec:
      containers:
        - name: cont1
          image: nginx
          command: ["/bin/bash", "-c", "sudo apt update -y; sleep 30"]
      restartPolicy: Never
