---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: swiggy
spec:
  containers:
    - name: cont1
      image: shaikmustafa/dm
      ports:
         -  containerPort: 80
  nodeSelector:
    node-id: node1

kubectl label node i-050070e4ca21b4b45 node-id=node1
kubectl create -f pod.yml
kubectl get pods 
kubectl get nodes
