---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: myrq
spec:
  hard:
    limits.cpu: "200m"
    requests.cpu: "150m"
    limits.memory: "38Mi"
    requests.memory: "12Mi"

kubectl create -f rq.yml -n dev
kubectl describe ns dev
kubectl get pod -n dev

------pod in ns------
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: cont1
      image: nginx
      resources:
        limits:
          memory: "20Mi"
          cpu: "50m"
        requests:
          memory: "10Mi"
          cpu: "30m"    
