---
apiVersion: v1
kind: Pod
metadata:
  name: POD-1
spec:
  containers:
    - name: cont1
      image: shaikmustafa/dm
      ports:
        -  containerPort: 80
      envFrom:
        - SecretRef:
          name: thirdsc



------------injecting entire secret to pod---------
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: cont1
      image: shaikmustafa/dm
      ports:
        -  containerPort: 80
      envFrom:
        - secretRef:
             name: thirdsc

 -----------injecting multiple keys to pod-------            

  apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
    - name: cont1
      image: shaikmustafa/dm
      env:
        - name: first
          valueFrom:
            secretKeyRef:
              name: firstsc
              key: dept

        - name: second
          valueFrom:
            secretKeyRef:
              name: secondsc
              key: user
           

-------------commands----------             

kubectl create secret generic firstsc --from-literal=app=zomato --from-literal=dept=food
kubectl describe secret firstsc
kubectl create secret generic secondsc --from-env-file=sc.env
echo "mysql" | base 64
