---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myfile
spec:
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
       labels:
         app: swiggy
    spec:
     containers:
       - name: cont1
         image: shaikmustafa/valluri:dbimage
         ports:
           - containerPort: 3306


---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 3306
      targetPort: 3306
~                                                                                                                                                                        
~                                      
