----host path in volumes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Welcome to DevOps class; sleep 10; done"]
           volumeMounts:
            - mountPath: /tmp/jenkins
              name: devops
        - name: cont2
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Welcome to DevOps class; sleep 10; done"]
          volumeMounts:
            - mountPath: /tmp/docker
              name: devops
      volumes:
        - name: devops
          hostPath:
            path: /tmp/mydata

 ---------volumes in emptydir-----
 volumes:
   - name: devops
     emptyDir: {}



-----volumes in pv & pvc-----
     volumes:
       - name: devops
         persistentVolumeClaim:
            claimName: mypvc1


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
      volumeID: vol-0c531e6a8c8bd34b0
      fsType: ext4


 ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 1Gi

~                                                                                                                                                                        
~                                                                                                                                                                        
~                      
                               
